### ISSUE TITLE
Screenshots of dash apps in README?

### ISSUE THREAD

**Issue by SamEdwardes** [Acrotrend/awesome-dash#30]
I think it would be helpful to include a screenshot of each app in the README under the link (In the App Examples section). This would help users decide which links they want to click on based on the apps design. 

Is this a change you would consider making? If so I am happy to creat a pull request.

**Comment by ucg8j** [comment]
Thanks for the suggestion. :)

Here are reasons against the proposal:
- Screen real-estate taken up by screenshots. If we have 40 awesome app links each with photos... this awesome list will feel more like flicking through instagram than a succinct categorised list of resources.
- Evaluating an application from a screenshot may be premature - don't judge an app by it's screenshot E.g. [Shiny](https://github.com/grabear/awesome-rshiny#app-examples), [Qlik](https://github.com/ambster-public/awesome-qlik#readme), [D3](https://github.com/wbkd/awesome-d3#readme), [dataviz](https://github.com/fasouto/awesome-dataviz#readme)
- A cursory search of other visualisation oriented awesome lists do not include screenshots
- Increases maintenance burden as app screnshots become out of date with an evolving app.

I am open for further suggestions and/or debate on the issue raised.

**Comment by SamEdwardes** [comment]
Thanks for the reply. Apologies I missed your initial response. Your reasons make sense. I think it would still be nice to have some kind of page with screenshots. But it is not necessary, still great to have this list!
