### ISSUE TITLE
Dash book and companion app

### ISSUE THREAD

**Issue by eliasdabbas** [Acrotrend/awesome-dash#37]
Hello, 
I just finished writing a [book about Dash](https://www.amazon.com/Interactive-Dashboards-Data-Apps-Plotly-ebook/dp/B08XMW45VY).  
The book is basically a single tutorial on how to build an app with a real-life dataset. 

I also [published the app](https://povertydata.org/). 

If you think this is relevant, where do you think they should go? 
The app could go under "App Examples", but I'm not sure about the book. 

Thanks.

**Comment by ucg8j** [comment]
Hey @eliasdabbas - sorry this dropped off my radar.
Happy for you to create a new sectionn "Books" below the existing section "Talks".

Nice work on publishing a book - I see it's getting good reviews on Amazon.
